"""empty message

Revision ID: ce037901eb00
Revises: 
Create Date: 2024-04-21 22:46:01.983319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce037901eb00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('icone', sa.String(length=256), nullable=True),
    sa.Column('url_midia', sa.String(length=256), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('residuo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('icone', sa.String(length=256), nullable=True),
    sa.Column('url_midia', sa.String(length=256), nullable=True),
    sa.Column('recolhido_em_ecoponto', sa.Boolean(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('termo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=256), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(length=256), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('equipe', sa.Boolean(), nullable=True),
    sa.Column('sistema', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('arte_publicitaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('url_midia', sa.String(length=256), nullable=False),
    sa.Column('disponibilizar_ecoponto', sa.Boolean(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_final', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('residuo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['residuo_id'], ['residuo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categoria_residuo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('residuo_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['residuo_id'], ['residuo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_fantasia', sa.String(), nullable=False),
    sa.Column('razao_social', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('ramo_atuacao', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('rede_social', sa.String(), nullable=True),
    sa.Column('participacao_outros_projetos', sa.Boolean(), nullable=True),
    sa.Column('descricao_outros_projetos', sa.String(), nullable=True),
    sa.Column('nome_contato_responsavel', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('nome_fantasia')
    )
    op.create_table('perfil_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=256), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('publicacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=256), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('url_media', sa.String(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_final', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('residuo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['residuo_id'], ['residuo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aceite_termo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aceite', sa.Boolean(), nullable=True),
    sa.Column('termo_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['termo_id'], ['termo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ecoponto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('aberto_publico', sa.Boolean(), nullable=True),
    sa.Column('situacao', sa.Enum('em_analise', 'aprovado', 'rejeitado', 'desativado', name='situacaoenum'), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_final', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secao_publicacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=256), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('url_media', sa.String(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_final', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('publicacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['publicacao_id'], ['publicacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dia_funcionamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Enum('dom', 'seg', 'ter', 'qua', 'qui', 'sex', 'sab', name='diassemanaenum'), nullable=True),
    sa.Column('hora_inicial', sa.Time(), nullable=True),
    sa.Column('hora_final', sa.Time(), nullable=True),
    sa.Column('ecoponto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ecoponto_id'], ['ecoponto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ecoponto_residuo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('residuo_id', sa.Integer(), nullable=False),
    sa.Column('ecoponto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ecoponto_id'], ['ecoponto.id'], ),
    sa.ForeignKeyConstraint(['residuo_id'], ['residuo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('localizacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rua', sa.String(length=256), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('bairro', sa.String(length=256), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=False),
    sa.Column('cidade', sa.String(length=256), nullable=False),
    sa.Column('estado', sa.String(length=256), nullable=False),
    sa.Column('complemento', sa.String(length=256), nullable=True),
    sa.Column('latitude', sa.String(length=256), nullable=False),
    sa.Column('longitude', sa.String(length=256), nullable=False),
    sa.Column('url_localizacao', sa.String(length=256), nullable=True),
    sa.Column('ecoponto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ecoponto_id'], ['ecoponto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecoponto_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('localizacao')
    op.drop_table('ecoponto_residuo')
    op.drop_table('dia_funcionamento')
    op.drop_table('secao_publicacao')
    op.drop_table('ecoponto')
    op.drop_table('aceite_termo')
    op.drop_table('publicacao')
    op.drop_table('perfil_usuario')
    op.drop_table('empresa')
    op.drop_table('categoria_residuo')
    op.drop_table('arte_publicitaria')
    op.drop_table('usuario')
    op.drop_table('termo')
    op.drop_table('residuo')
    op.drop_table('categoria')
    # ### end Alembic commands ###
